"""Document draft prompt — builds prompts and assembles Vietnamese administrative documents.

This module is pure Python with zero infrastructure dependencies.
Exports three public names:
  - DOCUMENT_TYPE_CONFIGS   — dict mapping document type codes to config dicts
  - build_document_draft_prompt(document_type, personal_data) -> str
  - assemble_document(document_type, personal_data, body_text, filing_jurisdiction) -> str

Supported document types (5):
  - don_xac_nhan_cu_tru     — Đơn xin xác nhận thông tin cư trú
  - don_dang_ky_thuong_tru  — Đơn đề nghị đăng ký thường trú
  - don_dang_ky_tam_tru     — Đơn đề nghị đăng ký tạm trú
  - don_khieu_nai           — Đơn khiếu nại
  - giay_cam_ket            — Giấy cam kết cư trú

Design contract:
  - The LLM writes ONLY the body section (max 400 tokens).
  - The structural wrapper (quốc hiệu, tiêu ngữ, personal data block, closing formula)
    is assembled by assemble_document() — never generated by the LLM.
  - Personal data is injected from session state — never hallucinated.
  - Missing personal data fields use [bracket] placeholders.

Vietnamese administrative document structure follows Nghị định 30/2020/NĐ-CP on
administrative document management.
"""

from __future__ import annotations

from datetime import date

# ---------------------------------------------------------------------------
# Document type configuration
# ---------------------------------------------------------------------------

DOCUMENT_TYPE_CONFIGS: dict[str, dict] = {
    "don_xac_nhan_cu_tru": {
        "ten_van_ban": "ĐƠN XIN XÁC NHẬN THÔNG TIN CƯ TRÚ",
        "kinh_gui": "Trưởng Công an phường/xã (hoặc UBND phường/xã)",
        "body_instruction": (
            "Viết phần nội dung đơn xin xác nhận thông tin cư trú. "
            "Nêu rõ: (1) mục đích cần xác nhận (để làm thủ tục hành "
            "chính, nộp hồ sơ, hoặc theo yêu cầu của cơ quan), "
            "(2) đề nghị cơ quan xác nhận thông tin cư trú hiện tại. "
            "Tối đa 120 từ. Văn phong hành chính trang trọng."
        ),
        "max_words": 120,
    },
    "don_dang_ky_thuong_tru": {
        "ten_van_ban": "ĐƠN ĐỀ NGHỊ ĐĂNG KÝ THƯỜNG TRÚ",
        "kinh_gui": "Trưởng Công an phường/xã nơi đề nghị đăng ký",
        "body_instruction": (
            "Viết phần nội dung đơn đề nghị đăng ký thường trú. "
            "Nêu rõ: (1) địa chỉ nơi đề nghị đăng ký thường trú, "
            "(2) lý do chuyển đến (công tác, gia đình, mua nhà, v.v.), "
            "(3) giấy tờ chứng minh chỗ ở hợp pháp đính kèm "
            "(hợp đồng thuê nhà/giấy tờ sở hữu). "
            "Tối đa 150 từ. Văn phong hành chính trang trọng."
        ),
        "max_words": 150,
    },
    "don_dang_ky_tam_tru": {
        "ten_van_ban": "ĐƠN ĐỀ NGHỊ ĐĂNG KÝ TẠM TRÚ",
        "kinh_gui": "Trưởng Công an phường/xã nơi đề nghị đăng ký",
        "body_instruction": (
            "Viết phần nội dung đơn đề nghị đăng ký tạm trú. "
            "Nêu rõ: (1) địa chỉ nơi đề nghị đăng ký tạm trú, "
            "(2) thời hạn tạm trú dự kiến, "
            "(3) lý do tạm trú (học tập, làm việc, ở nhờ người thân), "
            "(4) giấy tờ đính kèm (hợp đồng thuê nhà hoặc xác nhận "
            "của chủ hộ). "
            "Tối đa 150 từ. Văn phong hành chính trang trọng."
        ),
        "max_words": 150,
    },
    "don_khieu_nai": {
        "ten_van_ban": "ĐƠN KHIẾU NẠI",
        "kinh_gui": "Thủ trưởng cơ quan có thẩm quyền giải quyết",
        "body_instruction": (
            "Viết phần nội dung đơn khiếu nại. "
            "Nêu rõ: (1) quyết định hành chính hoặc hành vi hành "
            "chính bị khiếu nại — nếu không có thông tin cụ thể, "
            "dùng placeholder [nêu rõ nội dung quyết định/hành vi "
            "cần khiếu nại], (2) lý do cho rằng quyết định/hành vi "
            "đó là trái pháp luật hoặc không đúng, "
            "(3) yêu cầu cụ thể của người khiếu nại. "
            "Tối đa 200 từ. Văn phong hành chính trang trọng."
        ),
        "max_words": 200,
    },
    "giay_cam_ket": {
        "ten_van_ban": "GIẤY CAM KẾT CƯ TRÚ",
        "kinh_gui": "UBND phường/xã nơi cư trú",
        "body_instruction": (
            "Viết phần nội dung giấy cam kết cư trú. "
            "Nêu rõ: (1) cam kết chấp hành đúng quy định pháp luật "
            "về cư trú, (2) cam kết khai báo tạm vắng/tạm trú đúng "
            "thời hạn theo quy định, (3) cam kết chịu trách nhiệm "
            "trước pháp luật nếu vi phạm. "
            "Tối đa 120 từ. Văn phong hành chính trang trọng."
        ),
        "max_words": 120,
    },
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_FILING_JURISDICTION_MAP: dict[str, str] = {
    "VN-HCM": "TP. Hồ Chí Minh",
    "VN-HAN": "TP. Hà Nội",
    "VN-DN":  "TP. Đà Nẵng",
    "VN-CT":  "TP. Cần Thơ",
    "VN-HP":  "TP. Hải Phòng",
}


def _resolve_dia_danh(filing_jurisdiction: str | None) -> str:
    """Map a filing_jurisdiction code to a Vietnamese city/province name."""
    if not filing_jurisdiction or filing_jurisdiction == "VN":
        return ".........."
    # Check exact match first (e.g. "VN-HCM")
    if filing_jurisdiction in _FILING_JURISDICTION_MAP:
        return _FILING_JURISDICTION_MAP[filing_jurisdiction]
    # Check prefix match (e.g. "VN-HCM-26968" → "TP. Hồ Chí Minh")
    for prefix, name in _FILING_JURISDICTION_MAP.items():
        if filing_jurisdiction.startswith(prefix):
            return name
    return ".........."


def _format_date(value: object) -> str:
    """Format a date or date-string as DD/MM/YYYY for document output."""
    if value is None:
        return "[Ngày sinh]"
    if isinstance(value, date):
        return value.strftime("%d/%m/%Y")
    # Handle ISO strings like "1990-01-15"
    s = str(value)
    if len(s) == 10 and s[4] == "-" and s[7] == "-":
        try:
            parts = s.split("-")
            return f"{parts[2]}/{parts[1]}/{parts[0]}"
        except (IndexError, ValueError):
            pass
    return s or "[Ngày sinh]"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_document_draft_prompt(
    document_type: str,
    personal_data: dict,
) -> str:
    """Build the LLM system prompt for drafting the body section only.

    The LLM writes ONLY the body section. The structural wrapper
    (quốc hiệu, tiêu ngữ, personal data block, closing formula) is
    assembled by assemble_document(), not by the LLM.

    Args:
        document_type:  One of the DOCUMENT_TYPE_CONFIGS keys.
        personal_data:  Dict of personal data fields (may be empty).

    Returns:
        System prompt string to pass to LLMService.async_invoke().

    Raises:
        ValueError: If document_type is not in DOCUMENT_TYPE_CONFIGS.
    """
    if document_type not in DOCUMENT_TYPE_CONFIGS:
        raise ValueError(f"Unsupported document type: {document_type}")

    cfg = DOCUMENT_TYPE_CONFIGS[document_type]
    ten_van_ban = cfg["ten_van_ban"]
    body_instruction = cfg["body_instruction"]
    max_words = cfg["max_words"]

    return f"""Bạn là trợ lý soạn thảo văn bản hành chính Việt Nam.

## Nhiệm vụ
Soạn phần NỘI DUNG THÂN VĂN BẢN cho: **{ten_van_ban}**

## Hướng dẫn soạn thảo
{body_instruction}

## Giới hạn tối đa: {max_words} từ.

## Quy tắc bắt buộc
1. Chỉ viết phần nội dung thân văn bản.
   KHÔNG viết quốc hiệu, tiêu ngữ, thông tin cá nhân, hoặc phần ký tên
   — những phần đó đã được xử lý tự động bởi hệ thống.
2. KHÔNG bịa đặt thông tin cá nhân, số liệu, hoặc căn cứ pháp lý
   không có trong dữ liệu được cung cấp.
3. Sử dụng văn phong hành chính trang trọng, chuẩn mực.
4. Nếu thiếu thông tin cụ thể, dùng placeholder trong dấu ngoặc vuông
   ví dụ: [địa chỉ nơi đề nghị đăng ký], [lý do cụ thể].
5. Trả lời HOÀN TOÀN bằng tiếng Việt."""


def assemble_document(
    document_type: str,
    personal_data: dict,
    body_text: str,
    filing_jurisdiction: str | None = None,
) -> str:
    """Assemble a complete Vietnamese administrative document.

    Combines the standard structural wrapper (quốc hiệu, tiêu ngữ),
    personal data block, LLM-generated body, and closing formula
    per Nghị định 30/2020/NĐ-CP.

    Args:
        document_type:       One of the DOCUMENT_TYPE_CONFIGS keys.
        personal_data:       Dict of personal data fields (may be empty).
        body_text:           LLM-generated body section text.
        filing_jurisdiction: Optional scope code (e.g. "VN-HCM-26968").

    Returns:
        Complete document string ready for display or copy-paste.

    Raises:
        ValueError: If document_type is not in DOCUMENT_TYPE_CONFIGS.
    """
    if document_type not in DOCUMENT_TYPE_CONFIGS:
        raise ValueError(f"Unsupported document type: {document_type}")

    cfg = DOCUMENT_TYPE_CONFIGS[document_type]
    ten_van_ban = cfg["ten_van_ban"]
    kinh_gui = cfg["kinh_gui"]
    dia_danh = _resolve_dia_danh(filing_jurisdiction)

    ho_ten = personal_data.get("full_name") or "[Họ và tên]"
    ngay_sinh = _format_date(personal_data.get("date_of_birth"))
    so_cccd = personal_data.get("id_number") or "[Số CCCD/CMND]"
    dia_chi = personal_data.get("raw_address") or "[Địa chỉ thường trú]"
    ho_ten_ky = ho_ten  # same as ho_ten for the signature line

    return (
        "CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM\n"
        "Độc lập – Tự do – Hạnh phúc\n"
        "────────────────────────────\n"
        "\n"
        f"{ten_van_ban}\n"
        "\n"
        f"Kính gửi: {kinh_gui}\n"
        "\n"
        f"Tôi là: {ho_ten}\n"
        f"Ngày sinh: {ngay_sinh}\n"
        f"Số CCCD/CMND: {so_cccd}\n"
        f"Địa chỉ thường trú: {dia_chi}\n"
        "\n"
        f"{body_text}\n"
        "\n"
        "Tôi xin cam kết những thông tin trên là đúng sự thật\n"
        "và chịu trách nhiệm trước pháp luật về nội dung đã khai.\n"
        "\n"
        "Kính đề nghị Quý cơ quan xem xét và giải quyết.\n"
        "\n"
        "Trân trọng kính trình.\n"
        "\n"
        f"        {dia_danh}, ngày ... tháng ... năm ...\n"
        "                  Người làm đơn\n"
        "             (Ký và ghi rõ họ tên)\n"
        "\n"
        f"                  {ho_ten_ky}"
    )
