"""Form filler worker function — maps personal data to PDF form fields and fills the form.

Called by plan_executor_node via NODE_REGISTRY["form_filler_fn"].
This is a plain async function, NOT a LangGraph graph node — never add decorators.

Pipeline:
  1. Merge extracted_personal_data (latest OCR) into personal_data (accumulated)
     via SessionDataAccumulator.
  2. Look up the PDF template path for the target procedure.
  3. Get the form's fillable field names (hardcoded placeholder until TASK-15).
  4. Map PersonalData values to form fields via FormFieldMapper (LLM + cache).
  5. Fill the PDF via PDFService and write to tmp/ in MinIO.
  6. If all required fields are filled, promote to forms/{session_id}/{proc}.pdf.
     Otherwise leave in tmp/ and surface unfilled fields to the Synthesizer.
"""

from __future__ import annotations

import structlog

from app.agents.state import AgentState
from app.core.form_field_mapper import FormFieldMapper
from app.core.session_accumulator import SessionDataAccumulator

log = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Lazy service singletons
# Instantiated on first use so that import-time side effects are avoided and
# tests can patch these getters before form_filler_fn is called.
# ---------------------------------------------------------------------------

_llm_svc = None
_storage_svc = None
_pdf_svc = None


def _get_llm_svc():
    global _llm_svc
    if _llm_svc is None:
        from app.config import settings as _s
        from app.services.llm import LLMService
        _llm_svc = LLMService(backend=_s.LLM_BACKEND)
    return _llm_svc


def _get_storage_svc():
    global _storage_svc
    if _storage_svc is None:
        from app.services.storage_service import StorageService
        _storage_svc = StorageService()
    return _storage_svc


def _get_pdf_svc():
    global _pdf_svc
    if _pdf_svc is None:
        from app.services.pdf_service import PDFService
        _pdf_svc = PDFService(storage_service=_get_storage_svc())
    return _pdf_svc


# ---------------------------------------------------------------------------
# Form field and template definitions
# Matches the real CT01 form structure (Tờ khai thay đổi thông tin cư trú,
# Thông tư 66/2023/TT-BCA).  PDF templates live at:
#   backend/data/pdf_templates/{procedure_id}.pdf
# They are AcroForm PDFs generated by generate_templates.py; PDFService
# fills them via _fill_acroform() by the field names defined below.
# ---------------------------------------------------------------------------

PROCEDURE_TEMPLATE_PATHS: dict[str, str] = {
    "TTHC-001": "pdf_templates/TTHC-001.pdf",
    "TTHC-002": "pdf_templates/TTHC-002.pdf",
    "TTHC-003": "pdf_templates/TTHC-003.pdf",
}

PROCEDURE_FORM_FIELDS: dict[str, list[str]] = {
    # Đăng ký thường trú — CT01 fields (14 fields)
    "TTHC-001": [
        "ho_chu_dem_va_ten",
        "ngay_thang_nam_sinh",
        "gioi_tinh",
        "dan_toc",
        "so_dinh_danh_ca_nhan",
        "que_quan",
        "noi_thuong_tru",
        "noi_o_hien_tai",
        "nghe_nghiep",
        "noi_lam_viec",
        "ho_ten_chu_ho",
        "quan_he_voi_chu_ho",
        "so_dinh_danh_chu_ho",
        "noi_dung_de_nghi",
    ],
    # Đăng ký tạm trú — CT01 fields + thoi_han_tam_tru (15 fields)
    "TTHC-002": [
        "ho_chu_dem_va_ten",
        "ngay_thang_nam_sinh",
        "gioi_tinh",
        "dan_toc",
        "so_dinh_danh_ca_nhan",
        "que_quan",
        "noi_thuong_tru",
        "noi_o_hien_tai",
        "nghe_nghiep",
        "noi_lam_viec",
        "ho_ten_chu_ho",
        "quan_he_voi_chu_ho",
        "so_dinh_danh_chu_ho",
        "noi_dung_de_nghi",
        "thoi_han_tam_tru",   # TTHC-002 only — max 2 years
    ],
    # Xác nhận thông tin về cư trú — CT01 fields (14 fields)
    "TTHC-003": [
        "ho_chu_dem_va_ten",
        "ngay_thang_nam_sinh",
        "gioi_tinh",
        "dan_toc",
        "so_dinh_danh_ca_nhan",
        "que_quan",
        "noi_thuong_tru",
        "noi_o_hien_tai",
        "nghe_nghiep",
        "noi_lam_viec",
        "ho_ten_chu_ho",
        "quan_he_voi_chu_ho",
        "so_dinh_danh_chu_ho",
        "noi_dung_de_nghi",
    ],
}


# ---------------------------------------------------------------------------
# Worker function
# ---------------------------------------------------------------------------

async def form_filler_fn(state: AgentState) -> dict:
    """Fill a PDF form from accumulated PersonalData and return state updates.

    Reads: personal_data, extracted_personal_data, target_procedure_id, session_id
    Writes: personal_data (merged), filled_form_path, unfilled_required_fields,
            form_fill_complete, errors (on failure)
    """
    # ── Step 1: Merge incoming OCR data ──────────────────────────────────────
    accumulator = SessionDataAccumulator()
    effective_pd = accumulator.merge(
        state.get("personal_data"),
        state.get("extracted_personal_data"),
    )

    if effective_pd is None:
        log.warning("form_filler_fn: no personal data available")
        return {
            "personal_data": None,
            "filled_form_path": None,
            "unfilled_required_fields": [],
            "form_fill_complete": False,
            "errors": (state.get("errors") or []) + [
                "Không có dữ liệu cá nhân để điền vào biểu mẫu."
            ],
        }

    try:
        # ── Step 2: Look up template path ─────────────────────────────────────
        procedure_id: str | None = state.get("target_procedure_id")
        template_path = PROCEDURE_TEMPLATE_PATHS.get(procedure_id or "")
        if not template_path:
            log.warning(
                "form_filler_fn: no template for procedure",
                procedure_id=procedure_id,
            )
            return {
                "personal_data": effective_pd,
                "filled_form_path": None,
                "unfilled_required_fields": [],
                "form_fill_complete": False,
                "errors": (state.get("errors") or []) + [
                    "Không tìm thấy mẫu biểu cho thủ tục này."
                ],
            }

        # ── Step 3: Get form field names ──────────────────────────────────────
        form_field_names: list[str] = PROCEDURE_FORM_FIELDS.get(procedure_id or "", [])

        # ── Step 4: Map PersonalData → form fields ────────────────────────────
        form_mapper = FormFieldMapper(llm_service=_get_llm_svc())
        field_values = await form_mapper.map(
            personal_data=effective_pd,
            form_fields=form_field_names,
            form_id=procedure_id or "",
        )

        # ── Step 5: Identify unfilled required fields ─────────────────────────
        # All fields are treated as required until TASK-15 provides
        # required/optional metadata from real templates.
        unfilled = [f for f, v in field_values.items() if not v]

        # ── Step 6: Fill PDF and write to tmp/ ────────────────────────────────
        # PDFService.fill() is already async (it awaits download/upload via
        # StorageService), so it is awaited directly here.
        # NOTE: The TASK-08 spec described fill() as synchronous and expected
        # run_in_executor wrapping, but the existing implementation is async.
        pdf_svc = _get_pdf_svc()
        session_id: str = state["session_id"]
        tmp_path: str = await pdf_svc.fill(
            template_path,
            field_values,
            session_id,
            procedure_id or "",
        )

        # ── Step 7: Promote or hold ───────────────────────────────────────────
        if unfilled:
            # Partial fill — stay in tmp/ so Synthesizer can ask for missing data.
            filled_form_path = tmp_path
        else:
            # All fields filled — promote to permanent path.
            final_path = f"forms/{session_id}/{procedure_id}.pdf"
            await _get_storage_svc().promote_tmp(tmp_path, final_path)
            filled_form_path = final_path

        log.info(
            "form_filler_fn: complete",
            procedure_id=procedure_id,
            filled=len(field_values) - len(unfilled),
            unfilled=len(unfilled),
            promoted=len(unfilled) == 0,
        )

        return {
            "personal_data": effective_pd,
            "filled_form_path": filled_form_path,
            "unfilled_required_fields": unfilled,
            "form_fill_complete": len(unfilled) == 0,
        }

    except Exception as exc:
        log.warning("form_filler_fn: exception during fill", error=str(exc))
        return {
            "personal_data": effective_pd,
            "filled_form_path": None,
            "unfilled_required_fields": [],
            "form_fill_complete": False,
            "errors": (state.get("errors") or []) + [
                f"Lỗi khi điền biểu mẫu: {exc}"
            ],
        }
