"""Field configurations for all government form source files.

Single source of truth consumed by:
  - doc_filler.py  — knows which fields to look for in each .doc template
  - GET /api/v1/forms/configs/{procedure_id} — tells the frontend which tabs/fields to render

cccd_source values must exactly match PersonalData field names.
Available PersonalData fields from CCCD OCR:
  full_name, date_of_birth, gender, id_number, nationality,
  id_issue_date, id_issue_place, raw_address
"""

from __future__ import annotations

from typing import Literal, TypedDict


class FormFieldOption(TypedDict):
    value: str
    label: str


class FormField(TypedDict):
    id: str
    label: str
    field_type: Literal["text", "date", "year", "textarea", "select", "radio", "email", "tel"]
    cccd_source: str | None
    placeholder: str
    required: bool
    options: list[FormFieldOption] | None


class FormFileConfig(TypedDict):
    form_file: str
    tab_label: str
    procedure_ids: list[str]
    fields: list[FormField]


# ---------------------------------------------------------------------------
# 1. Tờ khai đăng ký khai sinh — TTHC-CR-001 (form 1 of 2)
# ---------------------------------------------------------------------------

_TKNGKKHAISINH: FormFileConfig = {
    "form_file": "1.TKngkkhaisinh.docx",
    "tab_label": "Tờ khai đăng ký khai sinh",
    "procedure_ids": ["TTHC-CR-001"],
    "fields": [
        # ── Người yêu cầu ──────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_yeu_cau",
            "label": "Họ, chữ đệm và tên người yêu cầu",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn B",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_nguoi_yeu_cau",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1990",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_nguoi_yeu_cau",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "giay_to_tuy_than_nguoi_yeu_cau",
            "label": "Giấy tờ tùy thân (số CCCD/Hộ chiếu)",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "quan_he_voi_nguoi_duoc_khai_sinh",
            "label": "Quan hệ với người được khai sinh",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Cha, Mẹ, Người được ủy quyền",
            "required": True,
            "options": None,
        },
        # ── Người được đăng ký khai sinh ───────────────────────────────────
        {
            "id": "ho_ten_tre",
            "label": "Họ, chữ đệm và tên",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_tre",
            "label": "Ngày, tháng, năm sinh (ghi bằng chữ)",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2024",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_tre",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": [{"value": "Nam", "label": "Nam"}, {"value": "Nữ", "label": "Nữ"}],
        },
        {
            "id": "dan_toc_tre",
            "label": "Dân tộc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": True,
            "options": None,
        },
        {
            "id": "quoc_tich_tre",
            "label": "Quốc tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Việt Nam",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_sinh",
            "label": "Nơi sinh",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Bệnh viện Từ Dũ, TP. Hồ Chí Minh",
            "required": True,
            "options": None,
        },
        {
            "id": "que_quan_tre",
            "label": "Quê quán",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Xã …, huyện …, tỉnh …",
            "required": True,
            "options": None,
        },
        # ── Người mẹ ──────────────────────────────────────────────────────
        {
            "id": "ho_ten_me",
            "label": "Họ, chữ đệm và tên người mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị C",
            "required": True,
            "options": None,
        },
        {
            "id": "nam_sinh_me",
            "label": "Năm sinh",
            "field_type": "year",
            "cccd_source": None,
            "placeholder": "VD: 1990",
            "required": True,
            "options": None,
        },
        {
            "id": "dan_toc_me",
            "label": "Dân tộc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_me",
            "label": "Quốc tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Việt Nam",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_me",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "giay_to_tuy_than_me",
            "label": "Giấy tờ tùy thân (số CCCD/Hộ chiếu)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        # ── Người cha ──────────────────────────────────────────────────────
        {
            "id": "ho_ten_cha",
            "label": "Họ, chữ đệm và tên người cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn B",
            "required": True,
            "options": None,
        },
        {
            "id": "nam_sinh_cha",
            "label": "Năm sinh",
            "field_type": "year",
            "cccd_source": None,
            "placeholder": "VD: 1988",
            "required": True,
            "options": None,
        },
        {
            "id": "dan_toc_cha",
            "label": "Dân tộc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_cha",
            "label": "Quốc tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Việt Nam",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_cha",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "giay_to_tuy_than_cha",
            "label": "Giấy tờ tùy thân (số CCCD/Hộ chiếu)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        # ── Thông tin bổ sung ──────────────────────────────────────────────
        {
            "id": "thong_tin_gcn_ket_hon",
            "label": "Thông tin Giấy chứng nhận kết hôn của cha, mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số GCN, ngày cấp, nơi cấp (nếu có)",
            "required": False,
            "options": None,
        },
        {
            "id": "yeu_cau_cap_ban_sao",
            "label": "Đề nghị cấp bản sao khai sinh",
            "field_type": "radio",
            "cccd_source": None,
            "placeholder": "",
            "required": False,
            "options": [{"value": "co", "label": "Có"}, {"value": "khong", "label": "Không"}],
        },
    ],
}

# ---------------------------------------------------------------------------
# 2. Tờ thông tin bổ sung đăng ký khai sinh — TTHC-CR-001 (form 2 of 2)
# ---------------------------------------------------------------------------

_TTT_NGKKHAISINH: FormFileConfig = {
    "form_file": "1.TTT-ngkkhaisinh.docx",
    "tab_label": "Tờ thông tin bổ sung đăng ký khai sinh",
    "procedure_ids": ["TTHC-CR-001"],
    "fields": [
        {
            "id": "ho_ten_tre",
            "label": "Họ tên của trẻ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_tre",
            "label": "Ngày tháng năm sinh",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2024",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_tre",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": [{"value": "Nam", "label": "Nam"}, {"value": "Nữ", "label": "Nữ"}],
        },
        {
            "id": "noi_sinh",
            "label": "Nơi sinh",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Bệnh viện …, tỉnh/thành phố …",
            "required": False,
            "options": None,
        },
        {
            "id": "ho_ten_nguoi_khai",
            "label": "Họ tên người khai",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn B",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_khai",
            "label": "Số định danh cá nhân của người khai",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "dia_chi_nguoi_khai",
            "label": "Địa chỉ người khai",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 3. Tờ khai yêu cầu cấp bản sao trích lục hộ tịch — TTHC-CR-002 (form 1 of 2)
# ---------------------------------------------------------------------------

_TK_YEUCAU_BANSAO: FormFileConfig = {
    "form_file": "18.TKyeucaubansaotrichluchotich.docx",
    "tab_label": "Tờ khai yêu cầu cấp bản sao trích lục",
    "procedure_ids": ["TTHC-CR-002"],
    "fields": [
        # ── Người yêu cầu ──────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_yeu_cau",
            "label": "Họ, chữ đệm và tên người yêu cầu",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_nguoi_yeu_cau",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1990",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_nguoi_yeu_cau",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_yeu_cau",
            "label": "Số định danh cá nhân / Số CCCD",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "quan_he_voi_nguoi_duoc_cap",
            "label": "Quan hệ với người được cấp bản sao Trích lục hộ tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Cha, Mẹ, Bản thân",
            "required": True,
            "options": None,
        },
        # ── Nội dung yêu cầu (về người được trích lục) ────────────────────
        {
            "id": "loai_giay_to_yeu_cau",
            "label": "Loại giấy tờ hộ tịch yêu cầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Giấy khai sinh, Giấy đăng ký kết hôn",
            "required": True,
            "options": None,
        },
        {
            "id": "ho_ten_nguoi_duoc_trich_luc",
            "label": "Họ, chữ đệm và tên người được đăng ký trong giấy tờ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_nguoi_duoc_trich_luc",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2000",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_nguoi_duoc_trich_luc",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": False,
            "options": [{"value": "Nam", "label": "Nam"}, {"value": "Nữ", "label": "Nữ"}],
        },
        {
            "id": "dan_toc_nguoi_duoc_trich_luc",
            "label": "Dân tộc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_nguoi_duoc_trich_luc",
            "label": "Quốc tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_nguoi_duoc_trich_luc",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "giay_to_tuy_than_nguoi_duoc_trich_luc",
            "label": "Giấy tờ tùy thân",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số CCCD / Hộ chiếu",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_dang_ky",
            "label": "Đã đăng ký tại (cơ quan đăng ký hộ tịch)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_dang_ky",
            "label": "Ngày tháng năm đăng ký",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2000",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dang_ky",
            "label": "Số đăng ký",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "001/2024/KS",
            "required": False,
            "options": None,
        },
        {
            "id": "quyen_so",
            "label": "Quyển số",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "01",
            "required": False,
            "options": None,
        },
        {
            "id": "thong_tin_khac",
            "label": "Thông tin khác",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "",
            "required": False,
            "options": None,
        },
        {
            "id": "so_ban_yeu_cau",
            "label": "Số lượng bản sao yêu cầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: 01",
            "required": True,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 4. Đơn/tờ thông tin cấp bản sao khai sinh/trích lục — TTHC-CR-002 (form 2 of 2)
# ---------------------------------------------------------------------------

_DTTT_CPBS: FormFileConfig = {
    "form_file": "18.DTTT-CpBSkhaisinhTrchlcHT.docx",
    "tab_label": "Đơn tờ thông tin cấp bản sao",
    "procedure_ids": ["TTHC-CR-002"],
    "fields": [
        # ── Người yêu cầu ──────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_yeu_cau",
            "label": "Họ và tên người yêu cầu",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ca_nhan",
            "label": "Số định danh cá nhân",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "giay_to_tuy_than_nguoi_yeu_cau",
            "label": "Giấy tờ tùy thân",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số CCCD / Hộ chiếu",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_thuong_tru",
            "label": "Nơi thường trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "quan_he_voi_nguoi_duoc_cap",
            "label": "Quan hệ với người được cấp",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Cha, Mẹ, Bản thân",
            "required": True,
            "options": None,
        },
        # ── Giấy tờ hộ tịch đã đăng ký ────────────────────────────────────
        {
            "id": "ho_ten_nguoi_duoc_dang_ky",
            "label": "Họ, chữ đệm và tên người được đăng ký",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_duoc_cap",
            "label": "Số định danh cá nhân (của người được đăng ký)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "giay_to_tuy_than_nguoi_duoc_cap",
            "label": "Giấy tờ tùy thân (của người được đăng ký)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số CCCD / Hộ chiếu",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_nguoi_duoc_cap",
            "label": "Nơi cư trú (của người được đăng ký)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "loai_van_ban_yeu_cau",
            "label": "Loại việc yêu cầu cấp bản sao",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Bản sao trích lục khai sinh",
            "required": True,
            "options": None,
        },
        {
            "id": "co_quan_da_dang_ky",
            "label": "Cơ quan đã đăng ký sự kiện hộ tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": True,
            "options": None,
        },
        {
            "id": "thong_tin_giay_to_ho_tich",
            "label": "Tên giấy tờ, số, quyển số, ngày đăng ký",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "VD: Giấy khai sinh số 01, quyển 01, ngày 01/01/2000",
            "required": True,
            "options": None,
        },
        {
            "id": "so_ban_yeu_cau",
            "label": "Số lượng bản sao",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "01",
            "required": True,
            "options": None,
        },
        {
            "id": "phuong_thuc_nhan_ket_qua",
            "label": "Phương thức nhận kết quả",
            "field_type": "radio",
            "cccd_source": None,
            "placeholder": "",
            "required": False,
            "options": [
                {"value": "truc_tiep", "label": "Nhận trực tiếp"},
                {"value": "buu_chinh", "label": "Qua bưu chính"},
            ],
        },
        {
            "id": "ho_so_dinh_kem",
            "label": "Hồ sơ đính kèm",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Liệt kê các giấy tờ đính kèm",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 5. Đơn xin nhận nuôi con nuôi — TTHC-AD-001 (form 1 of 2)
# ---------------------------------------------------------------------------

_DON_XIN_NHAN_NUOI: FormFileConfig = {
    "form_file": "1.nxinnhnconnui.docx",
    "tab_label": "Đơn xin nhận nuôi con nuôi",
    "procedure_ids": ["TTHC-AD-001"],
    "fields": [
        # ── Kính gửi ───────────────────────────────────────────────────────
        {
            "id": "kinh_gui",
            "label": "Kính gửi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Ủy ban nhân dân phường/xã...",
            "required": True,
            "options": None,
        },
        # ── Người nhận con nuôi — Ông ──────────────────────────────────────
        {
            "id": "ho_ten_ong",
            "label": "Họ, chữ đệm và tên (Ông)",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_ong",
            "label": "Ngày, tháng, năm sinh (Ông)",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1985",
            "required": True,
            "options": None,
        },
        {
            "id": "quoc_tich_ong",
            "label": "Quốc tịch (Ông)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Việt Nam",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ong",
            "label": "Số định danh cá nhân / Hộ chiếu (Ông)",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_ong",
            "label": "Nơi cư trú (Ông)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "dien_thoai_email_ong",
            "label": "Điện thoại / Thư điện tử (Ông)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "0912 345 678 / email@example.com",
            "required": False,
            "options": None,
        },
        # ── Người nhận con nuôi — Bà ───────────────────────────────────────
        {
            "id": "ho_ten_ba",
            "label": "Họ, chữ đệm và tên (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị B",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_ba",
            "label": "Ngày, tháng, năm sinh (Bà)",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1987",
            "required": True,
            "options": None,
        },
        {
            "id": "quoc_tich_ba",
            "label": "Quốc tịch (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Việt Nam",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ba",
            "label": "Số định danh cá nhân / Hộ chiếu (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "098765432101",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_ba",
            "label": "Nơi cư trú (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "dien_thoai_email_ba",
            "label": "Điện thoại / Thư điện tử (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "0987 654 321 / email@example.com",
            "required": False,
            "options": None,
        },
        # ── Người được nhận làm con nuôi ───────────────────────────────────
        {
            "id": "ho_ten_con_duoc_nhan_nuoi",
            "label": "Họ, chữ đệm và tên",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn C",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_con_duoc_nhan_nuoi",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": [{"value": "Nam", "label": "Nam"}, {"value": "Nữ", "label": "Nữ"}],
        },
        {
            "id": "ngay_sinh_con_duoc_nhan_nuoi",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2015",
            "required": True,
            "options": None,
        },
        {
            "id": "quoc_tich_con",
            "label": "Quốc tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Việt Nam",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_con",
            "label": "Số định danh cá nhân / Hộ chiếu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_sinh_con_duoc_nhan_nuoi",
            "label": "Nơi sinh",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Tỉnh/thành phố …",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_con",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "doi_tuong_con_nuoi",
            "label": "Thuộc đối tượng",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Mô tả đối tượng theo quy định (nếu có)",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 6. Văn bản xác nhận hoàn cảnh gia đình — TTHC-AD-001 (form 2 of 2)
# ---------------------------------------------------------------------------

_VB_XAC_NHAN_HOANCANH: FormFileConfig = {
    "form_file": "2.Vnbnxcnhnhoncnhgianhchiukinkinht.docx",
    "tab_label": "Văn bản xác nhận hoàn cảnh gia đình",
    "procedure_ids": ["TTHC-AD-001"],
    "fields": [
        # ── Người nhận con nuôi — Ông ──────────────────────────────────────
        {
            "id": "ho_ten_ong",
            "label": "Họ, chữ đệm và tên (Ông)",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_ong",
            "label": "Ngày, tháng, năm sinh (Ông)",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1985",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ong",
            "label": "Số định danh cá nhân (Ông)",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_thuong_tru_ong",
            "label": "Nơi thường trú (Ông)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_tam_tru_ong",
            "label": "Nơi tạm trú (Ông)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nếu khác nơi thường trú",
            "required": False,
            "options": None,
        },
        # ── Người nhận con nuôi — Bà ───────────────────────────────────────
        {
            "id": "ho_ten_ba",
            "label": "Họ, chữ đệm và tên (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị B",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_ba",
            "label": "Ngày, tháng, năm sinh (Bà)",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1987",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ba",
            "label": "Số định danh cá nhân (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "098765432101",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_thuong_tru_ba",
            "label": "Nơi thường trú (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_tam_tru_ba",
            "label": "Nơi tạm trú (Bà)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nếu khác nơi thường trú",
            "required": False,
            "options": None,
        },
        # ── Hoàn cảnh gia đình ─────────────────────────────────────────────
        {
            "id": "tinh_trang_hon_nhan",
            "label": "Tình trạng hôn nhân",
            "field_type": "radio",
            "cccd_source": None,
            "placeholder": "",
            "required": True,
            "options": [
                {"value": "chua_ket_hon", "label": "Chưa kết hôn"},
                {"value": "ket_hon", "label": "Đã kết hôn"},
                {"value": "ly_hon", "label": "Ly hôn"},
            ],
        },
        {
            "id": "con_de_con_nuoi",
            "label": "Số con đẻ / con nuôi hiện có",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: 1 con đẻ, 0 con nuôi",
            "required": False,
            "options": None,
        },
        {
            "id": "so_thanh_vien_song_cung",
            "label": "Số thành viên sống cùng",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "3",
            "required": True,
            "options": None,
        },
        {
            "id": "moi_quan_he_thanh_vien",
            "label": "Mối quan hệ gia đình của thành viên sống cùng",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "VD: Vợ/Chồng, Con ruột...",
            "required": False,
            "options": None,
        },
        {
            "id": "y_kien_thai_do_thanh_vien",
            "label": "Ý kiến, thái độ của thành viên với việc nhận con nuôi",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "",
            "required": False,
            "options": None,
        },
        # ── Tình trạng chỗ ở, điều kiện kinh tế ───────────────────────────
        {
            "id": "dien_tich_nha_o",
            "label": "Diện tích nhà ở (m²)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: 60",
            "required": True,
            "options": None,
        },
        {
            "id": "loai_nha_o",
            "label": "Loại nhà ở",
            "field_type": "radio",
            "cccd_source": None,
            "placeholder": "",
            "required": True,
            "options": [
                {"value": "so_huu", "label": "Sở hữu"},
                {"value": "thue", "label": "Thuê"},
                {"value": "khac", "label": "Khác"},
            ],
        },
        {
            "id": "co_khong_gian_cho_con_nuoi",
            "label": "Có không gian dành cho con nuôi",
            "field_type": "radio",
            "cccd_source": None,
            "placeholder": "",
            "required": True,
            "options": [{"value": "co", "label": "Có"}, {"value": "khong", "label": "Không"}],
        },
        {
            "id": "nghe_nghiep",
            "label": "Nghề nghiệp",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kỹ sư / Giáo viên …",
            "required": True,
            "options": None,
        },
        {
            "id": "thu_nhap_hang_thang",
            "label": "Thu nhập hàng tháng (nghìn đồng)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: 15.000 (lương) + 2.000 (phụ cấp)",
            "required": True,
            "options": None,
        },
        {
            "id": "tai_san_khac",
            "label": "Các tài sản khác",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Bất động sản, phương tiện, tiết kiệm...",
            "required": False,
            "options": None,
        },
        {
            "id": "dieu_kien_kinh_te_dam_bao",
            "label": "Điều kiện kinh tế đảm bảo cho việc nuôi dưỡng",
            "field_type": "radio",
            "cccd_source": None,
            "placeholder": "",
            "required": True,
            "options": [{"value": "co", "label": "Có"}, {"value": "khong", "label": "Không"}],
        },
    ],
}

# ---------------------------------------------------------------------------
# 7. Tờ khai đăng ký lại việc nuôi con nuôi — TTHC-AD-002
# ---------------------------------------------------------------------------

_TK_DKLAI_NUOICONNUOI: FormFileConfig = {
    "form_file": "7.Tkhaingklivicnuiconnui.docx",
    "tab_label": "Tờ khai đăng ký lại việc nuôi con nuôi",
    "procedure_ids": ["TTHC-AD-002"],
    "fields": [
        # ── Người yêu cầu ──────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_yeu_cau",
            "label": "Họ, chữ đệm và tên người yêu cầu",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_nguoi_yeu_cau",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1980",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_yeu_cau",
            "label": "Số định danh cá nhân / Hộ chiếu",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_nguoi_yeu_cau",
            "label": "Nơi cư trú",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        # ── Thông tin con nuôi ─────────────────────────────────────────────
        {
            "id": "ho_ten_con_nuoi",
            "label": "Họ, chữ đệm và tên con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn C",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_con_nuoi",
            "label": "Giới tính con nuôi",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": [{"value": "Nam", "label": "Nam"}, {"value": "Nữ", "label": "Nữ"}],
        },
        {
            "id": "ngay_sinh_con_nuoi",
            "label": "Ngày, tháng, năm sinh con nuôi",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2010",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_con_nuoi",
            "label": "Số định danh cá nhân / Hộ chiếu con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_sinh_con_nuoi",
            "label": "Nơi sinh con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Tỉnh/thành phố …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_con_nuoi",
            "label": "Nơi cư trú con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        # ── Cha nuôi ───────────────────────────────────────────────────────
        {
            "id": "ho_ten_cha_nuoi",
            "label": "Họ, chữ đệm và tên cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_cha_nuoi",
            "label": "Ngày, tháng, năm sinh cha nuôi",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1980",
            "required": True,
            "options": None,
        },
        {
            "id": "quoc_tich_cha_nuoi",
            "label": "Quốc tịch cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_cha_nuoi",
            "label": "Số định danh cá nhân / Hộ chiếu cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_cha_nuoi",
            "label": "Nơi cư trú cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        # ── Mẹ nuôi ───────────────────────────────────────────────────────
        {
            "id": "ho_ten_me_nuoi",
            "label": "Họ, chữ đệm và tên mẹ nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị B",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_me_nuoi",
            "label": "Ngày, tháng, năm sinh mẹ nuôi",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1982",
            "required": True,
            "options": None,
        },
        {
            "id": "quoc_tich_me_nuoi",
            "label": "Quốc tịch mẹ nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_me_nuoi",
            "label": "Số định danh cá nhân / Hộ chiếu mẹ nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "098765432101",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_cu_tru_me_nuoi",
            "label": "Nơi cư trú mẹ nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": True,
            "options": None,
        },
        # ── Thông tin đăng ký lần đầu ──────────────────────────────────────
        {
            "id": "noi_dang_ky_lan_dau",
            "label": "Đã đăng ký nuôi con nuôi tại",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dang_ky_lan_dau",
            "label": "Số Giấy chứng nhận / Quyết định",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "001/2015/NCN",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_cap_gcn",
            "label": "Ngày, tháng, năm cấp",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2015",
            "required": True,
            "options": None,
        },
        {
            "id": "nam_dang_ky_lan_dau",
            "label": "Năm đăng ký lần đầu",
            "field_type": "year",
            "cccd_source": None,
            "placeholder": "2015",
            "required": True,
            "options": None,
        },
        {
            "id": "co_quan_cap_gcn",
            "label": "Cơ quan cấp Giấy chứng nhận",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": True,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 8. Mẫu CT01 — Tờ khai thay đổi thông tin cư trú — TTHC-002, TTHC-003
# ---------------------------------------------------------------------------

_CT01: FormFileConfig = {
    "form_file": "1.MuCT01banhnhkmtheoThngts53.docx",
    "tab_label": "Tờ khai thay đổi thông tin cư trú (CT01)",
    "procedure_ids": ["TTHC-002", "TTHC-003"],
    "fields": [
        {
            "id": "kinh_gui",
            "label": "Kính gửi (cơ quan đăng ký cư trú)",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: Công an phường/xã...",
            "required": True,
            "options": None,
        },
        {
            "id": "ho_chu_dem_va_ten",
            "label": "Họ, chữ đệm và tên khai sinh",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_thang_nam_sinh",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1990",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": "gender",
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": [{"value": "Nam", "label": "Nam"}, {"value": "Nữ", "label": "Nữ"}],
        },
        {
            "id": "so_dinh_danh_ca_nhan",
            "label": "Số định danh cá nhân",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "12 chữ số",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dien_thoai",
            "label": "Số điện thoại liên hệ",
            "field_type": "tel",
            "cccd_source": None,
            "placeholder": "0912 345 678",
            "required": False,
            "options": None,
        },
        {
            "id": "email",
            "label": "Email",
            "field_type": "email",
            "cccd_source": None,
            "placeholder": "example@email.com",
            "required": False,
            "options": None,
        },
        {
            "id": "ho_ten_chu_ho",
            "label": "Họ, chữ đệm và tên chủ hộ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn B",
            "required": True,
            "options": None,
        },
        {
            "id": "quan_he_voi_chu_ho",
            "label": "Mối quan hệ với chủ hộ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Con / Vợ / Chồng …",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_chu_ho",
            "label": "Số định danh cá nhân của chủ hộ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "12 chữ số",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_dung_de_nghi",
            "label": "Nội dung đề nghị",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Nêu rõ nội dung đề nghị thay đổi thông tin cư trú",
            "required": True,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# Public exports
# ---------------------------------------------------------------------------

FORM_FILE_CONFIGS: dict[str, FormFileConfig] = {
    "1.TKngkkhaisinh.docx": _TKNGKKHAISINH,
    "1.TTT-ngkkhaisinh.docx": _TTT_NGKKHAISINH,
    "18.TKyeucaubansaotrichluchotich.docx": _TK_YEUCAU_BANSAO,
    "18.DTTT-CpBSkhaisinhTrchlcHT.docx": _DTTT_CPBS,
    "1.nxinnhnconnui.docx": _DON_XIN_NHAN_NUOI,
    "2.Vnbnxcnhnhoncnhgianhchiukinkinht.docx": _VB_XAC_NHAN_HOANCANH,
    "7.Tkhaingklivicnuiconnui.docx": _TK_DKLAI_NUOICONNUOI,
    "1.MuCT01banhnhkmtheoThngts53.docx": _CT01,
}

PROCEDURE_FORM_FILES: dict[str, list[str]] = {
    "TTHC-001": [],
    "TTHC-002": ["1.MuCT01banhnhkmtheoThngts53.docx"],
    "TTHC-003": ["1.MuCT01banhnhkmtheoThngts53.docx"],
    "TTHC-CR-001": [
        "1.TKngkkhaisinh.docx",
        "1.TTT-ngkkhaisinh.docx",
    ],
    "TTHC-CR-002": [
        "18.TKyeucaubansaotrichluchotich.docx",
        "18.DTTT-CpBSkhaisinhTrchlcHT.docx",
    ],
    "TTHC-AD-001": [
        "1.nxinnhnconnui.docx",
        "2.Vnbnxcnhnhoncnhgianhchiukinkinht.docx",
    ],
    "TTHC-AD-002": ["7.Tkhaingklivicnuiconnui.docx"],
}
