"""Field configurations for all government form source files.

Single source of truth consumed by:
  - doc_filler.py  — knows which fields to look for in each .doc template
  - GET /api/v1/forms/configs/{procedure_id} — tells the frontend which tabs/fields to render

cccd_source values must exactly match PersonalData field names.
Available PersonalData fields from CCCD OCR:
  full_name, date_of_birth, gender, id_number, nationality,
  id_issue_date, id_issue_place, raw_address
"""

from __future__ import annotations

from typing import Literal, TypedDict


class FormField(TypedDict):
    id: str
    label: str
    field_type: Literal["text", "date", "select", "textarea"]
    cccd_source: str | None
    placeholder: str
    required: bool
    options: list[str] | None


class FormFileConfig(TypedDict):
    form_file: str
    tab_label: str
    procedure_ids: list[str]
    fields: list[FormField]


# ---------------------------------------------------------------------------
# 1. Tờ khai đăng ký khai sinh — TTHC-CR-001 (form 1 of 2)
# ---------------------------------------------------------------------------

_TKNGKKHAISINH: FormFileConfig = {
    "form_file": "1.TKngkkhaisinh.doc",
    "tab_label": "Tờ khai đăng ký khai sinh",
    "procedure_ids": ["TTHC-CR-001"],
    "fields": [
        # ── Trẻ em được đăng ký ────────────────────────────────────────────
        {
            "id": "ho_ten_tre",
            "label": "Họ, chữ đệm và tên của trẻ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_tre",
            "label": "Ngày, tháng, năm sinh của trẻ",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2024",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_tre",
            "label": "Giới tính của trẻ",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": ["Nam", "Nữ"],
        },
        {
            "id": "noi_sinh",
            "label": "Nơi sinh",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Bệnh viện Từ Dũ, TP. Hồ Chí Minh",
            "required": True,
            "options": None,
        },
        {
            "id": "que_quan_tre",
            "label": "Quê quán của trẻ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Xã …, huyện …, tỉnh …",
            "required": False,
            "options": None,
        },
        {
            "id": "dan_toc_tre",
            "label": "Dân tộc của trẻ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_tre",
            "label": "Quốc tịch của trẻ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": False,
            "options": None,
        },
        # ── Cha ────────────────────────────────────────────────────────────
        {
            "id": "ho_ten_cha",
            "label": "Họ, chữ đệm và tên cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn B",
            "required": False,
            "options": None,
        },
        {
            "id": "ngay_sinh_cha",
            "label": "Ngày, tháng, năm sinh của cha",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1990",
            "required": False,
            "options": None,
        },
        {
            "id": "dan_toc_cha",
            "label": "Dân tộc của cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_cha",
            "label": "Quốc tịch của cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_cha",
            "label": "Số định danh cá nhân của cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "que_quan_cha",
            "label": "Quê quán của cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Xã …, huyện …, tỉnh …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_cha",
            "label": "Nơi cư trú của cha",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        # ── Mẹ ────────────────────────────────────────────────────────────
        {
            "id": "ho_ten_me",
            "label": "Họ, chữ đệm và tên mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị C",
            "required": False,
            "options": None,
        },
        {
            "id": "ngay_sinh_me",
            "label": "Ngày, tháng, năm sinh của mẹ",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1992",
            "required": False,
            "options": None,
        },
        {
            "id": "dan_toc_me",
            "label": "Dân tộc của mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_me",
            "label": "Quốc tịch của mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_me",
            "label": "Số định danh cá nhân của mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "098765432101",
            "required": False,
            "options": None,
        },
        {
            "id": "que_quan_me",
            "label": "Quê quán của mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Xã …, huyện …, tỉnh …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_me",
            "label": "Nơi cư trú của mẹ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        # ── Người đăng ký ──────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_dang_ky",
            "label": "Họ tên người đăng ký khai sinh",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn B",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_dang_ky",
            "label": "Số định danh cá nhân của người đăng ký",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_cu_tru_nguoi_dang_ky",
            "label": "Nơi cư trú của người đăng ký",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 2. Tờ thông tin bổ sung đăng ký khai sinh — TTHC-CR-001 (form 2 of 2)
# ---------------------------------------------------------------------------

_TTT_NGKKHAISINH: FormFileConfig = {
    "form_file": "1.TTT-ngkkhaisinh.doc",
    "tab_label": "Tờ thông tin bổ sung đăng ký khai sinh",
    "procedure_ids": ["TTHC-CR-001"],
    "fields": [
        {
            "id": "ho_ten_tre",
            "label": "Họ tên của trẻ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_tre",
            "label": "Ngày tháng năm sinh",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2024",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_tre",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": ["Nam", "Nữ"],
        },
        {
            "id": "noi_sinh",
            "label": "Nơi sinh",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Bệnh viện …, tỉnh/thành phố …",
            "required": False,
            "options": None,
        },
        {
            "id": "ho_ten_nguoi_khai",
            "label": "Họ tên người khai",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn B",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_khai",
            "label": "Số định danh cá nhân của người khai",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "dia_chi_nguoi_khai",
            "label": "Địa chỉ người khai",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 3. Tờ khai yêu cầu cấp bản sao trích lục hộ tịch — TTHC-CR-002 (form 1 of 2)
# ---------------------------------------------------------------------------

_TK_YEUCAU_BANSAO: FormFileConfig = {
    "form_file": "18.TKyeucaubansaotrichluchotich.doc",
    "tab_label": "Tờ khai yêu cầu cấp bản sao trích lục",
    "procedure_ids": ["TTHC-CR-002"],
    "fields": [
        # ── Người yêu cầu ──────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_yeu_cau",
            "label": "Họ, chữ đệm và tên người yêu cầu",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_nguoi_yeu_cau",
            "label": "Ngày, tháng, năm sinh của người yêu cầu",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1990",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_nguoi_yeu_cau",
            "label": "Giới tính người yêu cầu",
            "field_type": "select",
            "cccd_source": "gender",
            "placeholder": "Chọn giới tính",
            "required": False,
            "options": ["Nam", "Nữ"],
        },
        {
            "id": "so_dinh_danh_nguoi_yeu_cau",
            "label": "Số định danh cá nhân/Số CCCD người yêu cầu",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "dia_chi_thuong_tru_nguoi_yeu_cau",
            "label": "Địa chỉ thường trú của người yêu cầu",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dien_thoai",
            "label": "Số điện thoại",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "0912 345 678",
            "required": False,
            "options": None,
        },
        # ── Nội dung yêu cầu ───────────────────────────────────────────────
        {
            "id": "loai_giay_to_yeu_cau",
            "label": "Loại giấy tờ hộ tịch yêu cầu cấp bản sao",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Giấy khai sinh / Giấy chứng nhận kết hôn …",
            "required": True,
            "options": None,
        },
        {
            "id": "so_ban_yeu_cau",
            "label": "Số bản yêu cầu cấp",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "01",
            "required": True,
            "options": None,
        },
        {
            "id": "ho_ten_nguoi_can_trich_luc",
            "label": "Họ tên người được đăng ký trong giấy tờ hộ tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": True,
            "options": None,
        },
        {
            "id": "nam_dang_ky",
            "label": "Năm đăng ký",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "2024",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_dang_ky",
            "label": "Nơi đăng ký",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dang_ky",
            "label": "Số đăng ký",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "001/2024/KS",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 4. Đơn/tờ thông tin cấp bản sao khai sinh/trích lục — TTHC-CR-002 (form 2 of 2)
# ---------------------------------------------------------------------------

_DTTT_CPBS: FormFileConfig = {
    "form_file": "18.DTTT-CpBSkhaisinhTrchlcHT.doc",
    "tab_label": "Đơn tờ thông tin cấp bản sao",
    "procedure_ids": ["TTHC-CR-002"],
    "fields": [
        {
            "id": "ho_ten_nguoi_yeu_cau",
            "label": "Họ và tên người yêu cầu",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_thang_nam_sinh",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1990",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ca_nhan",
            "label": "Số định danh cá nhân",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "noi_thuong_tru",
            "label": "Nơi thường trú",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "loai_van_ban_yeu_cau",
            "label": "Loại văn bản yêu cầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Bản sao trích lục khai sinh",
            "required": True,
            "options": None,
        },
        {
            "id": "muc_dich_su_dung",
            "label": "Mục đích sử dụng",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Đăng ký nhập học / Làm hộ chiếu …",
            "required": False,
            "options": None,
        },
        {
            "id": "so_ban_yeu_cau",
            "label": "Số bản yêu cầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "01",
            "required": False,
            "options": None,
        },
        {
            "id": "nguoi_duoc_cap_ban_sao",
            "label": "Người được cấp bản sao",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn An",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_dang_ky_ho_tich",
            "label": "Nơi đăng ký hộ tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": False,
            "options": None,
        },
        {
            "id": "thong_tin_ho_tich",
            "label": "Thông tin hộ tịch",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Số đăng ký, năm đăng ký",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 5. Đơn xin nhận nuôi con nuôi — TTHC-AD-001 (form 1 of 2)
# ---------------------------------------------------------------------------

_DON_XIN_NHAN_NUOI: FormFileConfig = {
    "form_file": "1.nxinnhnconnui.doc",
    "tab_label": "Đơn xin nhận nuôi con nuôi",
    "procedure_ids": ["TTHC-AD-001"],
    "fields": [
        # ── Người nhận nuôi ────────────────────────────────────────────────
        {
            "id": "ho_ten_nguoi_nhan_nuoi",
            "label": "Họ tên người nhận nuôi",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_nguoi_nhan_nuoi",
            "label": "Ngày, tháng, năm sinh người nhận nuôi",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1985",
            "required": True,
            "options": None,
        },
        {
            "id": "so_dinh_danh_nguoi_nhan_nuoi",
            "label": "Số định danh cá nhân người nhận nuôi",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "dan_toc_nguoi_nhan_nuoi",
            "label": "Dân tộc người nhận nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "nghe_nghiep_nguoi_nhan_nuoi",
            "label": "Nghề nghiệp người nhận nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kỹ sư / Giáo viên …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_lam_viec",
            "label": "Nơi làm việc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Tên cơ quan, địa chỉ",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_thuong_tru_nguoi_nhan_nuoi",
            "label": "Nơi thường trú người nhận nuôi",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "tinh_trang_hon_nhan",
            "label": "Tình trạng hôn nhân",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Đã kết hôn / Chưa kết hôn …",
            "required": False,
            "options": None,
        },
        {
            "id": "ho_ten_vo_chong",
            "label": "Họ tên vợ/chồng",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị B",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_vo_chong",
            "label": "Số định danh cá nhân vợ/chồng",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "098765432101",
            "required": False,
            "options": None,
        },
        # ── Người được nhận làm con nuôi ───────────────────────────────────
        {
            "id": "ho_ten_con_duoc_nhan_nuoi",
            "label": "Họ tên người được nhận làm con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn C",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_con_duoc_nhan_nuoi",
            "label": "Ngày, tháng, năm sinh người được nhận làm con nuôi",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2015",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_con_duoc_nhan_nuoi",
            "label": "Giới tính người được nhận làm con nuôi",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": ["Nam", "Nữ"],
        },
        {
            "id": "dan_toc_con_duoc_nhan_nuoi",
            "label": "Dân tộc người được nhận làm con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_sinh_con_duoc_nhan_nuoi",
            "label": "Nơi sinh người được nhận làm con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Tỉnh/thành phố …",
            "required": False,
            "options": None,
        },
        {
            "id": "ly_do_xin_nhan_nuoi",
            "label": "Lý do xin nhận nuôi con nuôi",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Nêu rõ lý do xin nhận nuôi con nuôi",
            "required": True,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 6. Văn bản xác nhận hoàn cảnh gia đình — TTHC-AD-001 (form 2 of 2)
# ---------------------------------------------------------------------------

_VB_XAC_NHAN_HOANCANH: FormFileConfig = {
    "form_file": "2.Vnbnxcnhnhoncnhgianhchiukinkinht.doc",
    "tab_label": "Văn bản xác nhận hoàn cảnh gia đình",
    "procedure_ids": ["TTHC-AD-001"],
    "fields": [
        {
            "id": "ho_ten_nguoi_nuoi",
            "label": "Họ tên người nhận nuôi",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1985",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh",
            "label": "Số định danh cá nhân",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "dia_chi_thuong_tru",
            "label": "Địa chỉ thường trú",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "so_thanh_vien_gia_dinh",
            "label": "Số thành viên gia đình",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "3",
            "required": False,
            "options": None,
        },
        {
            "id": "dieu_kien_nha_o",
            "label": "Điều kiện nhà ở",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Mô tả điều kiện nhà ở hiện tại",
            "required": False,
            "options": None,
        },
        {
            "id": "thu_nhap_hang_thang",
            "label": "Thu nhập hàng tháng của gia đình",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "VD: 15.000.000 đồng/tháng",
            "required": False,
            "options": None,
        },
        {
            "id": "hoan_canh_gia_dinh",
            "label": "Hoàn cảnh gia đình",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Mô tả hoàn cảnh gia đình",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 7. Tờ khai đăng ký lại việc nuôi con nuôi — TTHC-AD-002
# ---------------------------------------------------------------------------

_TK_DKLAI_NUOICONNUOI: FormFileConfig = {
    "form_file": "7.Tkhaingklivicnuiconnui.doc",
    "tab_label": "Tờ khai đăng ký lại việc nuôi con nuôi",
    "procedure_ids": ["TTHC-AD-002"],
    "fields": [
        # ── Cha/mẹ nuôi ────────────────────────────────────────────────────
        {
            "id": "ho_ten_cha_nuoi",
            "label": "Họ tên cha nuôi",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_cha_nuoi",
            "label": "Ngày, tháng, năm sinh cha nuôi",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1980",
            "required": False,
            "options": None,
        },
        {
            "id": "dan_toc_cha_nuoi",
            "label": "Dân tộc cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "quoc_tich_cha_nuoi",
            "label": "Quốc tịch cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Việt Nam",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_cha_nuoi",
            "label": "Số định danh cá nhân cha nuôi",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": False,
            "options": None,
        },
        {
            "id": "que_quan_cha_nuoi",
            "label": "Quê quán cha nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Xã …, huyện …, tỉnh …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_thuong_tru",
            "label": "Nơi thường trú",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "ho_ten_me_nuoi",
            "label": "Họ tên mẹ nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Trần Thị B",
            "required": False,
            "options": None,
        },
        {
            "id": "ngay_sinh_me_nuoi",
            "label": "Ngày, tháng, năm sinh mẹ nuôi",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/1982",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_me_nuoi",
            "label": "Số định danh cá nhân mẹ nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "098765432101",
            "required": False,
            "options": None,
        },
        # ── Con nuôi ───────────────────────────────────────────────────────
        {
            "id": "ho_ten_con_nuoi",
            "label": "Họ tên con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn C",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_sinh_con_nuoi",
            "label": "Ngày, tháng, năm sinh con nuôi",
            "field_type": "date",
            "cccd_source": None,
            "placeholder": "01/01/2010",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh_con_nuoi",
            "label": "Giới tính con nuôi",
            "field_type": "select",
            "cccd_source": None,
            "placeholder": "Chọn giới tính",
            "required": True,
            "options": ["Nam", "Nữ"],
        },
        {
            "id": "dan_toc_con_nuoi",
            "label": "Dân tộc con nuôi",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        # ── Đăng ký lần đầu ────────────────────────────────────────────────
        {
            "id": "so_dang_ky_lan_dau",
            "label": "Số đăng ký lần đầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "001/2015/NCN",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_dang_ky_lan_dau",
            "label": "Nơi đăng ký lần đầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "UBND phường/xã …",
            "required": False,
            "options": None,
        },
        {
            "id": "nam_dang_ky_lan_dau",
            "label": "Năm đăng ký lần đầu",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "2015",
            "required": False,
            "options": None,
        },
        {
            "id": "ly_do_dang_ky_lai",
            "label": "Lý do đăng ký lại",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Lý do cần đăng ký lại (VD: hồ sơ bị mất, bị hủy …)",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# 8. Mẫu CT01 — Tờ khai thay đổi thông tin cư trú — TTHC-002, TTHC-003
# ---------------------------------------------------------------------------

_CT01: FormFileConfig = {
    "form_file": "1.MuCT01banhnhkmtheoThngts53.doc",
    "tab_label": "Tờ khai thay đổi thông tin cư trú (CT01)",
    "procedure_ids": ["TTHC-002", "TTHC-003"],
    "fields": [
        {
            "id": "ho_chu_dem_va_ten",
            "label": "Họ, chữ đệm và tên",
            "field_type": "text",
            "cccd_source": "full_name",
            "placeholder": "Nguyễn Văn A",
            "required": True,
            "options": None,
        },
        {
            "id": "ngay_thang_nam_sinh",
            "label": "Ngày, tháng, năm sinh",
            "field_type": "date",
            "cccd_source": "date_of_birth",
            "placeholder": "01/01/1990",
            "required": True,
            "options": None,
        },
        {
            "id": "gioi_tinh",
            "label": "Giới tính",
            "field_type": "select",
            "cccd_source": "gender",
            "placeholder": "Chọn giới tính",
            "required": False,
            "options": ["Nam", "Nữ"],
        },
        {
            "id": "dan_toc",
            "label": "Dân tộc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kinh",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_ca_nhan",
            "label": "Số định danh cá nhân",
            "field_type": "text",
            "cccd_source": "id_number",
            "placeholder": "012345678901",
            "required": True,
            "options": None,
        },
        {
            "id": "que_quan",
            "label": "Quê quán",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Xã …, huyện …, tỉnh …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_thuong_tru",
            "label": "Nơi thường trú",
            "field_type": "text",
            "cccd_source": "raw_address",
            "placeholder": "Số nhà, đường, phường, quận, thành phố",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_o_hien_tai",
            "label": "Nơi ở hiện tại",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nơi ở hiện tại nếu khác địa chỉ thường trú",
            "required": False,
            "options": None,
        },
        {
            "id": "nghe_nghiep",
            "label": "Nghề nghiệp",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Kỹ sư / Giáo viên …",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_lam_viec",
            "label": "Nơi làm việc",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Tên cơ quan, địa chỉ",
            "required": False,
            "options": None,
        },
        {
            "id": "ho_ten_chu_ho",
            "label": "Họ tên chủ hộ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Nguyễn Văn B",
            "required": False,
            "options": None,
        },
        {
            "id": "quan_he_voi_chu_ho",
            "label": "Quan hệ với chủ hộ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "Con / Vợ / Chồng …",
            "required": False,
            "options": None,
        },
        {
            "id": "so_dinh_danh_chu_ho",
            "label": "Số định danh cá nhân chủ hộ",
            "field_type": "text",
            "cccd_source": None,
            "placeholder": "012345678902",
            "required": False,
            "options": None,
        },
        {
            "id": "noi_dung_de_nghi",
            "label": "Nội dung đề nghị",
            "field_type": "textarea",
            "cccd_source": None,
            "placeholder": "Nêu rõ nội dung đề nghị thay đổi thông tin cư trú",
            "required": False,
            "options": None,
        },
    ],
}

# ---------------------------------------------------------------------------
# Public exports
# ---------------------------------------------------------------------------

FORM_FILE_CONFIGS: dict[str, FormFileConfig] = {
    "1.TKngkkhaisinh.doc": _TKNGKKHAISINH,
    "1.TTT-ngkkhaisinh.doc": _TTT_NGKKHAISINH,
    "18.TKyeucaubansaotrichluchotich.doc": _TK_YEUCAU_BANSAO,
    "18.DTTT-CpBSkhaisinhTrchlcHT.doc": _DTTT_CPBS,
    "1.nxinnhnconnui.doc": _DON_XIN_NHAN_NUOI,
    "2.Vnbnxcnhnhoncnhgianhchiukinkinht.doc": _VB_XAC_NHAN_HOANCANH,
    "7.Tkhaingklivicnuiconnui.doc": _TK_DKLAI_NUOICONNUOI,
    "1.MuCT01banhnhkmtheoThngts53.doc": _CT01,
}

PROCEDURE_FORM_FILES: dict[str, list[str]] = {
    "TTHC-001": [],
    "TTHC-002": ["1.MuCT01banhnhkmtheoThngts53.doc"],
    "TTHC-003": ["1.MuCT01banhnhkmtheoThngts53.doc"],
    "TTHC-CR-001": [
        "1.TKngkkhaisinh.doc",
        "1.TTT-ngkkhaisinh.doc",
    ],
    "TTHC-CR-002": [
        "18.TKyeucaubansaotrichluchotich.doc",
        "18.DTTT-CpBSkhaisinhTrchlcHT.doc",
    ],
    "TTHC-AD-001": [
        "1.nxinnhnconnui.doc",
        "2.Vnbnxcnhnhoncnhgianhchiukinkinht.doc",
    ],
    "TTHC-AD-002": ["7.Tkhaingklivicnuiconnui.doc"],
}
